Using cang 14.0.6

diff --git a/tools/clang_tidy/BUILD b/tools/clang_tidy/BUILD
--- a/tools/clang_tidy/BUILD
+++ b/tools/clang_tidy/BUILD
@@ -2,11 +2,14 @@ load("//tools/bazel_build:binary_wrapper.bzl", "sh_binary_wrapper")
 
 sh_binary_wrapper(
     name = "clang_tidy",
-    binary = "@linux_x86_64_clang_14_0_0//:clang_tidy",
+    binary = "//toolchains/cc/linux_x86_64_clang:clang_tidy",
     command = """
         ln -s $RUNFILES_DIR/__main__/external external
         ln -s $RUNFILES_DIR/__main__/.clang-tidy .clang-tidy
-        {binary} --use-color --quiet "${{@: 2}}" 2> /dev/null
+        if ! {{ error=$({binary} --use-color --quiet "${{@: 2}}" 2>&1 >&3); }} 3>&1; then
+            echo "$error"
+            exit 1
+        fi
         touch "$1"
     """,
     data = [
