Adding schedule

diff --git a/.gitea/actions/opencode/action.yml b/.gitea/actions/opencode/action.yml
--- a/.gitea/actions/opencode/action.yml
+++ b/.gitea/actions/opencode/action.yml
@@ -33,11 +33,10 @@ runs:
               echo  "==== prompt ================================================="
               echo "$PROMPT"
               echo  "==== processing ============================================="
-              #bzd-lease opencode run --dangerously-skip-permissions --agent "$AGENT" "$PROMPT" > /tmp/agent-response.txt || {
-              #  echo "==== Opencode failed, dumping last log ======================"
-              #  tail -n 100 "$(ls -t ~/.local/share/opencode/log/*.log 2>/dev/null | head -n 1)" || echo "No log found"
-              #  exit 1
-              #}
-              echo "{\"vulnerability_found\":true,\"title\":\"test\",\"severity\": \"Critical\"}" > /tmp/agent-response.txt
+              bzd-lease opencode run --dangerously-skip-permissions --agent "$AGENT" "$PROMPT" > /tmp/agent-response.txt || {
+                echo "==== Opencode failed, dumping last log ======================"
+                tail -n 100 "$(ls -t ~/.local/share/opencode/log/*.log 2>/dev/null | head -n 1)" || echo "No log found"
+                exit 1
+              }
               echo  "==== response ==============================================="
               cat /tmp/agent-response.txt
